import {
  IconAlertTriangle,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBook,
  IconCheck,
  IconChartBar as IconChart,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCopy,
  IconCreditCard,
  IconDeviceFloppy as IconSave,
  IconDownload,
  IconEye as IconView,
  IconFile,
  IconFileText,
  IconFilter,
  IconGitBranch,
  IconHelpCircle,
  IconLink,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconPencil,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconLogout,
  IconMenu,
  IconLayout,
  IconPalette,
  IconCode,
  IconBuilding,
  IconTag,
  IconDatabase,
  IconForms,
  IconDots as IconEllipsisVertical,
  IconTable
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCode,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  file: IconFile,
  fileText: IconFileText,
  user: IconUser,
  settings: IconSettings,
  logout: IconLogout,
  media: IconPhoto,
  folder: IconFile,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  ellipsisVertical: IconEllipsisVertical,
  add: IconPlus,
  plus: IconPlus,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  arrowLeft: IconArrowLeft,
  arrowUp: IconArrowUp,
  arrowDown: IconArrowDown,
  help: IconHelpCircle,
  check: IconCheck,
  sun: IconSun,
  moon: IconMoon,
  twitter: IconBrandTwitter,
  github: IconBrandGithub,
  userCircle: IconUserCircle,
  userEdit: IconUserEdit,
  menu: IconMenu,
  page: IconLayout,
  palette: IconPalette,
  code: IconCode,
  userPen: IconUserEdit,
  building: IconBuilding,
  tag: IconTag,
  database: IconDatabase,
  form: IconForms,
  pencil: IconPencil,
  copy: IconCopy,
  refresh: IconRefresh,
  download: IconDownload,
  upload: IconUpload,
  search: IconSearch,
  view: IconView,
  chart: IconChart,
  link: IconLink,
  gitBranch: IconGitBranch,
  save: IconSave,
  table: IconTable,
  book: IconBook,
  filter: IconFilter
};
