export const AppSettings = {
    serviceBase: "https://mixcore.net",
    apiVersion: "v2",
  };
  
  export const NgAppSettings = {
    serviceBase: "",
    encryptKey: "MbQeThWmZq4t7w!z$C&F)J@NcRfUjXn2",
    encryptIV: "3s6v9y$B&E)H@McQ",
    clientId: "ngAuthApp",
    facebookAppId: "",
    request: {
      pageSize: "20",
      pageIndex: 0,
      status: "Published",
      orderBy: "CreatedDateTime",
      direction: "Desc",
      fromDate: null,
      toDate: null,
      keyword: "",
      key: "",
      query: {},
    },
    restRequest: {
      pageSize: "20",
      pageIndex: 0,
      status: "Published",
      orderBy: "CreatedDateTime",
      direction: "Desc",
      fromDate: null,
      toDate: null,
      keyword: "",
      query: {},
    },
    privacies: ["VND", "USD"],
    pageSizes: ["", "5", "10", "15", "20"],
    directions: [
      {
        value: "Asc",
        title: "Asc",
      },
      {
        value: "Desc",
        title: "Desc",
      },
    ],
    orders: [
      {
        value: "CreatedDateTime",
        title: "Created Date",
      },
      {
        value: "Priority",
        title: "Priority",
      },
      {
        value: "Title",
        title: "Title",
      },
    ],
    contentStatuses: ["Deleted", "Preview", "Published", "Draft", "Schedule"],
    dataTypes: [
      { title: "Custom", value: "Custom" },
      { title: "DateTime", value: "DateTime" },
      { title: "Date", value: "Date" },
      { title: "Time", value: "Time" },
      { title: "Duration", value: "Duration" },
      { title: "Phone Number", value: "PhoneNumber" },
      { title: "Currency", value: "Currency" },
      { title: "Text", value: "Text" },
      { title: "Html", value: "Html" },
      { title: "Multiline Text", value: "MultilineText" },
      { title: "Email Address", value: "EmailAddress" },
      { title: "Password", value: "Password" },
      { title: "Url", value: "Url" },
      { title: "Image Url", value: "ImageUrl" },
      { title: "Credit Card", value: "CreditCard" },
      { title: "PostalCode", value: "PostalCode" },
      { title: "Upload", value: "Upload" },
      { title: "Color", value: "Color" },
      { title: "Boolean", value: "Boolean" },
      { title: "Icon", value: "Icon" },
      { title: "Video Youtube", value: "VideoYoutube" },
      { title: "Tui Editor", value: "TuiEditor" },
      { title: "Integer", value: "Integer" },
      { title: "QR Code", value: "QRCode" },
      { title: "Reference", value: "Reference" },
    ],
    icons: [],
  };